name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data ingestion
        run: python scripts/ingest_data.py

      - name: Run model training
        run: python scripts/train_model.py

      - name: Run model evaluation
        run: python scripts/evaluate_model.py
