[tool.poetry]
name = "n1-cand-merc"
version = "0.1.0"
description = ""
authors = ["hellum55 <hellum.christian@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
